name: CI

on: [push, pull_request]

jobs:
  test_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
      - name: Install tox
        run: pip install tox
      - name: Running app tests
        run: tox
        
